name: Rendre gradlew exécutable (temporaire, à supprimer)

on:
  push:
    paths:
      - .github/workflows/fix-exec.yml

permissions:
  contents: write

jobs:
  fix:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git update-index --chmod=+x gradlew
          git commit -m "Rendre gradlew exécutable"
          git push
